"""add degree_plans additional_credit_hours

Revision ID: 999172b788e5
Revises: 745ad80a45f7
Create Date: 2026-08-14 01:25:57.327668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999172b788e5'
down_revision: Union[str, Sequence[str], None] = '745ad80a45f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degree_plans', sa.Column('additional_credit_hours', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('degree_plans', 'additional_credit_hours')
    # ### end Alembic commands ###
