"""initial schema

Revision ID: a1d053466018
Revises: 
Create Date: 2026-08-12 01:33:48.598526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d053466018'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('college_code', sa.String(length=30), nullable=False),
    sa.Column('college_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('college_id'),
    sa.UniqueConstraint('college_code')
    )
    op.create_table('course_groups',
    sa.Column('course_group_id', sa.Integer(), nullable=False),
    sa.Column('course_group_code', sa.String(length=60), nullable=False),
    sa.Column('course_group_name', sa.String(length=250), nullable=False),
    sa.Column('course_group_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('course_group_id'),
    sa.UniqueConstraint('course_group_code')
    )
    op.create_table('course_tags',
    sa.Column('course_tag_id', sa.Integer(), nullable=False),
    sa.Column('parent_course_tag_id', sa.Integer(), nullable=True),
    sa.Column('tag_code', sa.String(length=60), nullable=False),
    sa.Column('tag_name', sa.String(length=200), nullable=False),
    sa.Column('tag_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_course_tag_id'], ['course_tags.course_tag_id'], ),
    sa.PrimaryKeyConstraint('course_tag_id'),
    sa.UniqueConstraint('tag_code')
    )
    op.create_table('requirement_sets',
    sa.Column('requirement_set_id', sa.Integer(), nullable=False),
    sa.Column('requirement_set_code', sa.String(length=60), nullable=False),
    sa.Column('requirement_set_name', sa.String(length=250), nullable=False),
    sa.Column('requirement_set_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('requirement_set_id'),
    sa.UniqueConstraint('requirement_set_code')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('terms',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('term_type', sa.String(length=10), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('term_id'),
    sa.UniqueConstraint('sequence_index'),
    sa.UniqueConstraint('term_code')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_code', sa.String(length=30), nullable=False),
    sa.Column('department_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.college_id'], ),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_code')
    )
    op.create_table('planning_scenarios',
    sa.Column('planning_scenario_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=200), nullable=True),
    sa.Column('start_term_id', sa.Integer(), nullable=True),
    sa.Column('target_graduation_term_id', sa.Integer(), nullable=True),
    sa.Column('default_minimum_credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('default_maximum_credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('full_time_minimum_credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('allow_summer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['start_term_id'], ['terms.term_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['target_graduation_term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('planning_scenario_id')
    )
    op.create_table('academic_programs',
    sa.Column('academic_program_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=60), nullable=False),
    sa.Column('program_name', sa.String(length=250), nullable=False),
    sa.Column('program_type', sa.String(length=20), nullable=False),
    sa.Column('total_credit_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('academic_program_id'),
    sa.UniqueConstraint('program_code')
    )
    op.create_table('degree_plans',
    sa.Column('degree_plan_id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_credit_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('projected_graduation_term_id', sa.Integer(), nullable=True),
    sa.Column('solver_objective_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('solver_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.planning_scenario_id'], ),
    sa.ForeignKeyConstraint(['projected_graduation_term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('degree_plan_id')
    )
    op.create_table('scenario_objectives',
    sa.Column('scenario_objective_id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=False),
    sa.Column('objective_type', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.planning_scenario_id'], ),
    sa.PrimaryKeyConstraint('scenario_objective_id')
    )
    op.create_table('scenario_terms',
    sa.Column('scenario_term_id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('minimum_credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('maximum_credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.planning_scenario_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('scenario_term_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_code')
    )
    op.create_table('academic_program_relationships',
    sa.Column('academic_program_relationship_id', sa.Integer(), nullable=False),
    sa.Column('parent_program_id', sa.Integer(), nullable=False),
    sa.Column('child_program_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['child_program_id'], ['academic_programs.academic_program_id'], ),
    sa.ForeignKeyConstraint(['parent_program_id'], ['academic_programs.academic_program_id'], ),
    sa.PrimaryKeyConstraint('academic_program_relationship_id')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('course_number', sa.String(length=20), nullable=False),
    sa.Column('course_level', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=250), nullable=False),
    sa.Column('credit_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('course_description', sa.Text(), nullable=True),
    sa.Column('fall_offered', sa.Boolean(), nullable=False),
    sa.Column('spring_offered', sa.Boolean(), nullable=False),
    sa.Column('summer_offered', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('course_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('overlap_policies',
    sa.Column('overlap_policy_id', sa.Integer(), nullable=False),
    sa.Column('program_a_id', sa.Integer(), nullable=True),
    sa.Column('program_b_id', sa.Integer(), nullable=True),
    sa.Column('requirement_set_a_id', sa.Integer(), nullable=True),
    sa.Column('requirement_set_b_id', sa.Integer(), nullable=True),
    sa.Column('policy_type', sa.String(length=40), nullable=False),
    sa.Column('credit_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_a_id'], ['academic_programs.academic_program_id'], ),
    sa.ForeignKeyConstraint(['program_b_id'], ['academic_programs.academic_program_id'], ),
    sa.ForeignKeyConstraint(['requirement_set_a_id'], ['requirement_sets.requirement_set_id'], ),
    sa.ForeignKeyConstraint(['requirement_set_b_id'], ['requirement_sets.requirement_set_id'], ),
    sa.PrimaryKeyConstraint('overlap_policy_id')
    )
    op.create_table('program_requirement_sets',
    sa.Column('program_requirement_set_id', sa.Integer(), nullable=False),
    sa.Column('academic_program_id', sa.Integer(), nullable=False),
    sa.Column('requirement_set_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_program_id'], ['academic_programs.academic_program_id'], ),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_sets.requirement_set_id'], ),
    sa.PrimaryKeyConstraint('program_requirement_set_id')
    )
    op.create_table('scenario_programs',
    sa.Column('scenario_program_id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=False),
    sa.Column('academic_program_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_program_id'], ['academic_programs.academic_program_id'], ),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.planning_scenario_id'], ),
    sa.PrimaryKeyConstraint('scenario_program_id')
    )
    op.create_table('course_group_courses',
    sa.Column('course_group_course_id', sa.Integer(), nullable=False),
    sa.Column('course_group_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_group_id'], ['course_groups.course_group_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('course_group_course_id')
    )
    op.create_table('course_relations',
    sa.Column('course_relation_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('related_course_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('maximum_combined_credits', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['related_course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('course_relation_id')
    )
    op.create_table('course_rule_nodes',
    sa.Column('course_rule_node_id', sa.Integer(), nullable=False),
    sa.Column('target_course_id', sa.Integer(), nullable=False),
    sa.Column('parent_rule_node_id', sa.Integer(), nullable=True),
    sa.Column('requisite_type', sa.String(length=30), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('rule_operator', sa.String(length=10), nullable=True),
    sa.Column('required_course_id', sa.Integer(), nullable=True),
    sa.Column('required_count', sa.Integer(), nullable=True),
    sa.Column('minimum_grade', sa.String(length=5), nullable=True),
    sa.Column('minimum_total_credits', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('required_subject_id', sa.Integer(), nullable=True),
    sa.Column('minimum_course_level', sa.Integer(), nullable=True),
    sa.Column('minimum_standing', sa.String(length=20), nullable=True),
    sa.Column('required_academic_program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_rule_node_id'], ['course_rule_nodes.course_rule_node_id'], ),
    sa.ForeignKeyConstraint(['required_academic_program_id'], ['academic_programs.academic_program_id'], ),
    sa.ForeignKeyConstraint(['required_course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['required_subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['target_course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('course_rule_node_id')
    )
    op.create_table('course_tag_map',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['course_tag_id'], ['course_tags.course_tag_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'course_tag_id')
    )
    op.create_table('plan_courses',
    sa.Column('plan_course_id', sa.Integer(), nullable=False),
    sa.Column('degree_plan_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('credit_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('placement_source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['degree_plan_id'], ['degree_plans.degree_plan_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('plan_course_id')
    )
    op.create_table('requirement_nodes',
    sa.Column('requirement_node_id', sa.Integer(), nullable=False),
    sa.Column('requirement_set_id', sa.Integer(), nullable=False),
    sa.Column('parent_requirement_node_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('node_operator', sa.String(length=10), nullable=True),
    sa.Column('node_name', sa.String(length=250), nullable=True),
    sa.Column('required_course_id', sa.Integer(), nullable=True),
    sa.Column('course_group_id', sa.Integer(), nullable=True),
    sa.Column('required_credit_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('required_count', sa.Integer(), nullable=True),
    sa.Column('minimum_grade', sa.String(length=5), nullable=True),
    sa.Column('minimum_course_level', sa.Integer(), nullable=True),
    sa.Column('minimum_distinct_subjects', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_group_id'], ['course_groups.course_group_id'], ),
    sa.ForeignKeyConstraint(['parent_requirement_node_id'], ['requirement_nodes.requirement_node_id'], ),
    sa.ForeignKeyConstraint(['required_course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_sets.requirement_set_id'], ),
    sa.PrimaryKeyConstraint('requirement_node_id')
    )
    op.create_table('scenario_preferences',
    sa.Column('scenario_preference_id', sa.Integer(), nullable=False),
    sa.Column('planning_scenario_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.String(length=40), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['planning_scenario_id'], ['planning_scenarios.planning_scenario_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('scenario_preference_id')
    )
    op.create_table('optimization_messages',
    sa.Column('optimization_message_id', sa.Integer(), nullable=False),
    sa.Column('degree_plan_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message_code', sa.String(length=60), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('requirement_node_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['degree_plan_id'], ['degree_plans.degree_plan_id'], ),
    sa.ForeignKeyConstraint(['requirement_node_id'], ['requirement_nodes.requirement_node_id'], ),
    sa.PrimaryKeyConstraint('optimization_message_id')
    )
    op.create_table('student_credits',
    sa.Column('student_credit_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('external_course_code', sa.String(length=60), nullable=True),
    sa.Column('external_course_title', sa.String(length=250), nullable=True),
    sa.Column('credits_earned', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('is_in_residence', sa.Boolean(), nullable=False),
    sa.Column('approved_requirement_node_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_requirement_node_id'], ['requirement_nodes.requirement_node_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('student_credit_id')
    )
    op.create_table('requirement_allocations',
    sa.Column('requirement_allocation_id', sa.Integer(), nullable=False),
    sa.Column('degree_plan_id', sa.Integer(), nullable=False),
    sa.Column('requirement_node_id', sa.Integer(), nullable=False),
    sa.Column('plan_course_id', sa.Integer(), nullable=True),
    sa.Column('student_credit_id', sa.Integer(), nullable=True),
    sa.Column('credit_hours_applied', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['degree_plan_id'], ['degree_plans.degree_plan_id'], ),
    sa.ForeignKeyConstraint(['plan_course_id'], ['plan_courses.plan_course_id'], ),
    sa.ForeignKeyConstraint(['requirement_node_id'], ['requirement_nodes.requirement_node_id'], ),
    sa.ForeignKeyConstraint(['student_credit_id'], ['student_credits.student_credit_id'], ),
    sa.PrimaryKeyConstraint('requirement_allocation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_allocations')
    op.drop_table('student_credits')
    op.drop_table('optimization_messages')
    op.drop_table('scenario_preferences')
    op.drop_table('requirement_nodes')
    op.drop_table('plan_courses')
    op.drop_table('course_tag_map')
    op.drop_table('course_rule_nodes')
    op.drop_table('course_relations')
    op.drop_table('course_group_courses')
    op.drop_table('scenario_programs')
    op.drop_table('program_requirement_sets')
    op.drop_table('overlap_policies')
    op.drop_table('courses')
    op.drop_table('academic_program_relationships')
    op.drop_table('subjects')
    op.drop_table('scenario_terms')
    op.drop_table('scenario_objectives')
    op.drop_table('degree_plans')
    op.drop_table('academic_programs')
    op.drop_table('planning_scenarios')
    op.drop_table('departments')
    op.drop_table('terms')
    op.drop_table('students')
    op.drop_table('requirement_sets')
    op.drop_table('course_tags')
    op.drop_table('course_groups')
    op.drop_table('colleges')
    # ### end Alembic commands ###
