"""add planning_scenarios enforce_program_credit_minimum

Revision ID: e72bac3a2d86
Revises: 999172b788e5
Create Date: 2026-08-14 06:37:00.905614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72bac3a2d86'
down_revision: Union[str, Sequence[str], None] = '999172b788e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "planning_scenarios",
        sa.Column("enforce_program_credit_minimum", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column("planning_scenarios", "enforce_program_credit_minimum", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_scenarios', 'enforce_program_credit_minimum')
    # ### end Alembic commands ###
